---
- name: Ensure appadmin user, sudoers config, and app directory
  hosts: localhost
  become: yes
  vars:
    functional_user: appadmin
    app_dir: /opt/app
    sudoers_file: "/etc/sudoers.d/{{ functional_user }}"
    sudo_rule: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: /bin/su - {{ functional_user }}"
  tasks:
    - name: Ensure the functional user exists
      ansible.builtin.user:
        name: "{{ functional_user }}"
        shell: /bin/bash
        create_home: yes
        groups: "{{ 'sudo' if 'debian' in ansible_os_family | lower else 'wheel' }}"
        append: yes
        password_lock: true
    - name: Add sudoers rule for current user
      ansible.builtin.copy:
        content: "{{ sudo_rule }}"
        dest: "{{ sudoers_file }}"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'
    - name: Ensure app directory exists
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ functional_user }}"
        group: "{{ functional_user }}"
        mode: '0755'
